spring:
  application:
    name: eureka-server
---
spring:
  profiles: eurekaserver1
server:
  port: 8701
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8702/eureka/
---
spring:
  profiles: eurekaserver2
server:
  port: 8702
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8701/eureka/